src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchaseCreateDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/Approval.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/PurchaseMember.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/PurchasePosition.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/CorrespondentRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/ItemRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/StorageRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/common/PositionNameEx.java

중복된 이름으로 인해 Position의 클래스명을 수정했습니다.

Position 클래스명 수정

---

src/main/java/com/varc/brewnetapp/domain/order/query/controller/HQOrderController.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderService.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- order mapper 수정
- order mapper 수정

order mapper 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchaseItemDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchaseRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/PurchaseApproval.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/PurchaseItem.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/ApprovalRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/CorrespondentRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/ItemRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchaseMemberRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/StorageRepository.java

- Approval -> PurchaseApproval
- Item -> PurchaseItem

중복된 클래스명 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/aggregate/PurchaseApproval.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/ApprovalRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/CorrespondentItemRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchaseApprovalRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchaseItemRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchaseMemberRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchasePositionRepository.java

발주(구매품의서) 등록 및 결재 요청 기능
- 발주서 겸 구매품의서 작성
- 발주 넣을 거래처 선택
- 해당 거래처의 품목들 중 발주할 품목들 선택 후 수량 입력
- 총 발주금액 자동 계산
- 등록된 구매품의서의 결재 상태는 UNCONFIRMED

발주(구매품의서) 등록 및 결재 요청 기능 추가

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/LetterOfPurchaseItemRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/LetterOfPurchaseRepository.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/domain/repository/PurchaseItemRepository.java

[PURCHASE] 발주 관련 완료된 기능

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/InHousePurchasePrintRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchasePrintResponseDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

[PURCHASE] 내부용 발주서 출력에 대한 데이터 응답

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

[PURCHASE] 회계부서로 구매품의서 발송

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchaseRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/dto/PurchaseApproverMemberDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/mapper/PurchaseMapper.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/exception/ApprovalNotFoundException.java
src/main/resources/com/varc/brewnetapp/domain/purchase/query/mapper/PurchaseMapper.xml

- 발주 등록 시 requestDTO에서 결재 구분 제외
- 결재라인(결재 구분) 선택하면 해당 결재라인의 결재자 목록 반환하는 api 추가

[PURCHASE] 발주 등록 기능 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/query/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/dto/LetterOfPurchaseDetailDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/common/PageResponse.java
src/main/java/com/varc/brewnetapp/domain/storage/common/SearchStorageCriteria.java
src/main/java/com/varc/brewnetapp/domain/storage/query/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/query/dto/StorageDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/query/dto/StorageDetailDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/query/dto/StorageNameDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/query/mapper/StorageMapper.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/storage/query/mapper/StorageMapper.xml

[STORAGE] 창고 목록/상세 조회 기능

---

src/main/java/com/varc/brewnetapp/domain/storage/common/SearchItemStockCriteria.java
src/main/java/com/varc/brewnetapp/domain/storage/query/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/query/dto/StockDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/query/mapper/StorageMapper.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/storage/query/mapper/StorageMapper.xml

[STORAGE] 창고별 상품 재고 리스트 조회 기능

---

src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/domain/repository/StockRepository.java
src/main/java/com/varc/brewnetapp/domain/storage/command/domain/repository/StorageRepository.java

[STORAGE] 창고 수정/삭제 기능

---

src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/dto/ChangeStockRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java

[STORAGE] 창고별 상품의 재고 조정 기능

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

- 구매품의서 등록 시 신규 등록된 구매품의서 코드를 결과로 반환하도록 수정
- 
- 구매품의서 등록 시 신규 등록된 구매품의서 코드를 결과로 반환하도록 수정했습니다.
- 사진을 업로드해주세요

[PURCHASE] 구매품의서 등록 시 신규 등록된 구매품의서 코드를 결과로 반환하도록 수정

---

src/main/java/com/varc/brewnetapp/domain/storage/common/SearchStorageCriteria.java
src/main/java/com/varc/brewnetapp/domain/storage/query/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/query/service/StorageServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/storage/query/mapper/StorageMapper.xml

- 창고 코드로도 창고 검색 및 목록 조회 가능하도록 수정
- #86 
- 창고명 뿐만 아니라 창고 코드로도 창고 검색 및 목록 조회 가능하도록 수정했습니다.
- 사진을 업로드해주세요

[STORAGE] 창고 코드로도 창고 검색 및 목록 조회 가능하도록 수정

---

src/main/java/com/varc/brewnetapp/domain/order/query/controller/HQOrderQueryController.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderDetailForHQDTO.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderItem.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryService.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

가맹점의 주문 상세 조회

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/ChangeInStockToAvailableRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/dto/ChangeStockRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java

- 발주 상품 입고 처리하는 api request 수정
- #75 
- RequestParam으로 요청했던 것을 RequestBody로 요청하는 것으로 수정했습니다.
- 사진을 업로드해주세요

[PURCHASE] 발주 상품 입고 처리하는 api request 수정

---

src/main/java/com/varc/brewnetapp/domain/order/command/application/controller/FranchiseOrderController.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/dto/orderrequest/OrderRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderService.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java

- 주문 요청 시, franchiseCode 토큰으로 조회
- 변경 전: 가맹점에서 franchiseCode 전달
- 변경 후: 서버가 요청받은 토큰의 loginId를 파싱하여 franchiseCode 조회
- 사진을 업로드해주세요

가맹점의 주문 등록 시, 요청 포맷 수정

---

src/main/java/com/varc/brewnetapp/domain/order/query/controller/HQOrderQueryController.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/FranchiseOrderDTO.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderApprovalHistoryDTO.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryService.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

주문 결재 내역 조회

---

src/main/java/com/varc/brewnetapp/domain/order/command/application/controller/HQOrderController.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- collection 필드 속성 수정
- 사진을 업로드해주세요

collection 필드 속성 수정

---

src/main/java/com/varc/brewnetapp/domain/member/query/dto/MemberDTO.java
src/main/java/com/varc/brewnetapp/domain/member/query/mapper/MemberMapper.java
src/main/java/com/varc/brewnetapp/domain/member/query/service/MemberServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/member/query/mapper/MemberMapper.xml

[Member] 회원 정보 상세 조회 수정 (가맹점 회원도 반환됨)

---

src/main/java/com/varc/brewnetapp/common/GlobalExceptionHandler.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/controller/HQSuperController.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderService.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/domain/repository/StockRepository.java
src/main/java/com/varc/brewnetapp/exception/InvalidStockException.java
src/main/java/com/varc/brewnetapp/exception/OrderApprovalNotFound.java
src/main/java/com/varc/brewnetapp/exception/OrderDraftAlreadyApproved.java

- 주문 요청 승인에 따른 재고 변동
- 주문 요청 승인에 따른 재고 변동
- 사진을 업로드해주세요

주문 요청 승인에 따른 재고 변동

---

src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderDetailForHQDTO.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- 본사의 주문 상세조회 수정
- 수정 전
{
"status": 200,
"message": "OK",
"result": {
"orderCode": 16,
"createdAt": "2024-11-02 10:10:50",
"franchiseName": "CoffeeHouse C",
"comment": null,
"managerName": "User Three",
"sumPrice": 100000,
"orderItemList": [
{
"itemCode": 1,
"quantity": 10,
"partSum": 0,
"name": "Item 1",
"categoryName": "Sub Category 1"
},
{
"itemCode": 2,
"quantity": 5,
"partSum": 0,
"name": "Item 2",
"categoryName": "Sub Category 2"
},
{
"itemCode": 3,
"quantity": 8,
"partSum": 0,
"name": "Item 3",
"categoryName": "Sub Category 3"
}
]
}
}
- 수정 후:
{
"status": 200,
"message": "OK",
"result": {
"orderCode": 16,
"createdAt": "2024-11-02 10:10:50",
"franchiseName": "CoffeeHouse C",
"comment": null,
"managerName": "User Three",
"sumPrice": 100000,
"orderStatus": "APPROVED",
"statusDate": …

본사의 주문 상세조회 수정

---

src/main/java/com/varc/brewnetapp/domain/order/command/application/controller/FranchiseOrderController.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderApprovalHistoryDTO.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- 주문 결재 상신 시, 응답값 수정
- tbl_order_approver의 복합키 정보 응답 추가
- 사진을 업로드해주세요

주문 결재 상신 시, 응답값 수정

---

src/main/java/com/varc/brewnetapp/domain/order/command/application/controller/HQOrderController.java
src/main/java/com/varc/brewnetapp/domain/order/command/application/service/OrderServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/member/query/mapper/MemberValidateMapper.xml

- member validate service 수정
- member validate service 수정
- 사진을 업로드해주세요

member validate service 수정

---

src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/dto/CorrespondentRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/domain/repository/CorrespondentRepository.java

- 거래처 등록 기능 오류 수정
- #56 
- 거래처 등록 시 modelmapper 관련 오류 수정
- 사진을 업로드해주세요

[FACTORY] 거래처 등록 기능 오류 수정

---

src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/domain/repository/CorrespondentRepository.java

- 거래처 정보 수정 기능 개발
- #57 
- 거래처 정보 수정 기능 개발 완료
- 사진을 업로드해주세요

[FACTORY] 거래처 정보 수정 기능 개발

---

src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/dto/CorrespondentDeleteRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/domain/repository/CorrespondentItemRepository.java

- 거래처 삭제 기능 개발
- #58 
- 거래처 삭제 기능 개발 완료 (연결된 상품 있으면 삭제 불가)
- 사진을 업로드해주세요

[FACTORY] 거래처 삭제 기능 개발

---

src/main/java/com/varc/brewnetapp/domain/correspondent/query/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.xml

- 거래처 목록 엑셀 파일 출력을 위한 api 개발
- 
- 거래처 목록을 엑셀 파일로 출력할 때 필요한 api 개발 완료
- 사진을 업로드해주세요

[FACTORY] 거래처 목록 엑셀 파일 출력을 위한 api 개발

---

src/main/java/com/varc/brewnetapp/common/GlobalExceptionHandler.java
src/main/java/com/varc/brewnetapp/domain/order/query/controller/FranchiseOrderQueryController.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/OrderSearchDTO.java
src/main/java/com/varc/brewnetapp/domain/order/query/dto/SearchCriteria.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderCounterMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryService.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java
src/main/java/com/varc/brewnetapp/exception/InvalidCriteriaException.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderCounterMapper.xml
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- 가맹점의 주문 검색
- 가맹점의 주문 검색 - 주문 코드
- 가맹점의 주문 검색 - 품목 명
- 사진을 업로드해주세요

가맹점의 주문 검색

---

src/main/java/com/varc/brewnetapp/domain/correspondent/common/SearchCorrespondentCriteria.java
src/main/java/com/varc/brewnetapp/domain/correspondent/common/SearchCorrespondentItemCriteria.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.xml

- 거래처의 발주 가능 상품 목록 출력을 위한 api 개발
- 
- 특정 거래처의 활성화된 상품 목록을 엑셀 파일로 출력 시 사용하는 api 개발 완료
- 사진을 업로드해주세요

[FACTORY] 거래처의 발주 가능 상품 목록 출력을 위한 api 개발

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchasePrintItemDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/dto/LetterOfPurchaseDetailDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/dto/PurchaseItemDTO.java

- 발주서 출력 API 수정
- 
- 외부용 발주서 출력 시 사용되는 출력 미리보기 API와 출력내역 저장 API 분리
- 그 외 자잘한 수정
- 사진을 업로드해주세요

[PURCHASE] 발주서 출력 API 수정

---

src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/dto/CorrespondentRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.xml

- 거래처 상세정보 API 수정
- 
- 거래처 상세정보 API 등 일부 수정
- 사진을 업로드해주세요

fix: 거래처 상세정보 API 수정

---

src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/dto/CorrespondentRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/correspondent/command/application/service/CorrespondentServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/controller/CorrespondentController.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentService.java
src/main/java/com/varc/brewnetapp/domain/correspondent/query/service/CorrespondentServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/correspondent/query/mapper/CorrespondentMapper.xml

- 거래처 관련 dto 수정
- 
- modelmapper 오류로 인한 거래처 관련 dto 필드 수정
- 사진을 업로드해주세요

fix: 거래처 관련 dto 수정

---

src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/dto/StorageDeleteRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java

- 창고 삭제 api 수정
- #85 
- 창고 삭제 api의 pathVariable -> requestBody 수정
- 사진을 업로드해주세요

fix: 창고 삭제 api 수정

---

src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java

- 창고 삭제 로직 수정
- #85 
- 창고 service의 삭제 로직 수정
- 사진을 업로드해주세요

fix: 창고 삭제 로직 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/dto/PurchaseCancelRequestDTO.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

- 구매품의서 결재 요청 취소 api 수정
- #69 
- 구매품의서 결재 요청 취소 api의 pathVariable -> requestBody 수정
- 사진을 업로드해주세요

fix: 구매품의서 결재 요청 취소 api 수정

---

src/main/java/com/varc/brewnetapp/domain/order/query/controller/HQOrderQueryController.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryService.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java

- 본사 주문 조회(엑셀용) 수정 
- 로그인 이아디로 가맹점 조회 삭제
- 본사에서 주문 목록 조회 시, 로그인 이아디로 가맹점 조회 로직 삭제
- 사진을 업로드해주세요

본사 주문 조회(엑셀용) 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/controller/StorageController.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageService.java
src/main/java/com/varc/brewnetapp/domain/storage/command/application/service/StorageServiceImpl.java

- 창고별 상품 재고 조정 api 수정
- #89 
- 창고별 상품 재고 조정 시, 상품 List가 아닌 개별 dto로 받도록 수정
- 사진을 업로드해주세요

fix: 창고별 상품 재고 조정 api 수정

---

src/main/java/com/varc/brewnetapp/domain/order/query/controller/HQOrderQueryController.java
src/main/java/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.java
src/main/java/com/varc/brewnetapp/domain/order/query/service/OrderQueryServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/order/query/mapper/OrderMapper.xml

- 가맹점 검색 쿼리 수정
- 페이지네이션 미적용 시 검색결과 조회 결과 0
- 페이지네이션 미적용 시, 검색 조건 필터링 적용X
- 사진을 업로드해주세요

가맹점 검색 쿼리 수정

---

src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeApproverVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningApproverVO.java
src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 교환/반품 결재진행상태 API 수정
- 교환/반품 결재진행상태 API 수정
- X
- 사진을 업로드해주세요

fix: 교환/반품 결재진행상태 API 수정

---

src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeDetailVO.java
src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeHistoryVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/RefundHistoryVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningDetailVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningHistoryVO.java
src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 교환/반품 상세조회 시 status 확인 가능하도록 수정
- 교환/반품 상세조회 시 status 확인 가능하도록 수정
- X
- 사진을 업로드해주세요

[EXCHANGE] 상세조회 API 수정

---

src/main/java/com/varc/brewnetapp/domain/returning/command/application/service/ReturningServiceImpl.java

- 반품시 주문별상품 AVAILABLE 상태값 변경 로직 삭제
- 반품시 주문별상품 AVAILABLE 상태값 변경 로직 삭제
- X
- 사진을 업로드해주세요

fix: 반품시 주문별상품 AVAILABLE 상태값 변경 로직 삭제

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

- 발주 승인 시 창고별 재고에 없는 상품이면 새로 등록
- 
- 창고 생성 이후에 새로 등록된 상품은 창고별 재고에 존재하지 않으므로 발주 승인 시 재고를 새로 등록
- 사진을 업로드해주세요

fix: 발주 승인 시 창고별 재고에 없는 상품이면 새로 등록

---

src/main/java/com/varc/brewnetapp/domain/purchase/command/application/service/PurchaseServiceImpl.java

- 구매품의서 반려 시 에러 처리 수정
- 
- 구매품의서 반려 시 에러 처리 수정(결재자가 아니면 반려 처리 불가)
- 사진을 업로드해주세요

fix: 구매품의서 반려 시 에러 처리 수정

---

src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 가맹점 교환/반품내역 상세조회 쿼리 수정
- 가맹점 교환/반품내역 상세조회 쿼리 수정
- X
- 사진을 업로드해주세요

hotfix: 가맹점 교환/반품내역 상세조회 쿼리 수정

---

src/main/java/com/varc/brewnetapp/domain/exchange/command/application/service/ExchangeServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeApproverVO.java
src/main/java/com/varc/brewnetapp/domain/returning/command/application/service/ReturningServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml

- 결재신청 결재상태 변경하도록 수정(취소 고려)
- 결재신청 결재상태 변경하도록 수정(취소 고려)
- X
- 사진을 업로드해주세요

hotfix: 결재신청 결재상태 변경하도록 수정(취소 고려)

---

src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeHistoryDetailVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/RefundHistoryDetailVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningHistoryDetailVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningHistoryItemVO.java
src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 교환/반품 타부서 상세조회 시 교환/반품코드 포함
- X
- 교환/반품 타부서 상세조회 시 교환/반품코드 포함
- X
- 사진을 업로드해주세요

hotfix: 교환/반품 타부서 상세조회 시 교환/반품코드 포함

---

src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningHistoryItemVO.java

- ReturningHistoryItemVO 수정
- X
- ReturningHistoryItemVO 수정
- X
- 사진을 업로드해주세요

hotfix: ReturningHistoryItemVO 수정

---

src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/RefundHistoryDetailVO.java
src/main/java/com/varc/brewnetapp/domain/returning/query/aggregate/vo/ReturningHistoryDetailVO.java
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 반품 타부서 처리내역 상세조회 VO에 confirmed 추가
- X
- 반품 타부서 처리내역 상세조회 VO에 confirmed 추가
- X
- 사진을 업로드해주세요

hotfix: 반품 타부서 처리내역 상세조회 VO에 confirmed 추가

---

src/main/java/com/varc/brewnetapp/domain/exchange/command/application/service/ExchangeServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeDetailVO.java
src/main/java/com/varc/brewnetapp/domain/exchange/query/aggregate/vo/ExchangeItemVO.java
src/main/java/com/varc/brewnetapp/domain/returning/command/application/service/ReturningServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml

- 본사 교환/반품 결재승인 에러 수정
- X
- 본사 교환/반품 결재승인 에러 수정
- X
- 사진을 업로드해주세요

[EXCHANGE] 본사 교환/반품 결재승인 에러 수정

---

src/main/resources/com/varc/brewnetapp/domain/exchange/query/mapper/ExchangeMapper.xml
src/main/resources/com/varc/brewnetapp/domain/returning/query/mapper/ReturningMapper.xml

- 교환/반품 상세조회 - 물품조회 쿼리 수정
- X
- 교환/반품 상세조회 - 물품조회 쿼리 수정
- X
- 사진을 업로드해주세요

fix: 교환/반품 상세조회 - 물품조회 쿼리 수정

---

src/main/java/com/varc/brewnetapp/domain/returning/command/application/service/ReturningServiceImpl.java

- 반품 재고변동 수정
-X
- 반품 재고변동 수정
- X
- 사진을 업로드해주세요

fix: 반품 재고변동 수정

---

src/main/java/com/varc/brewnetapp/domain/purchase/query/controller/PurchaseController.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/mapper/PurchaseMapper.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/service/PurchaseService.java
src/main/java/com/varc/brewnetapp/domain/purchase/query/service/PurchaseServiceImpl.java
src/main/resources/com/varc/brewnetapp/domain/purchase/query/mapper/PurchaseMapper.xml

- 미결재 발주 내역 목록 조회 기능 추가
- #71 
- 미결재 발주 내역 목록 조회 기능 추가
- 사진을 업로드해주세요

[PURCHASE] 미결재 발주 내역 목록 조회 기능 추가

---

src/main/java/com/varc/brewnetapp/domain/exchange/command/application/service/ExchangeServiceImpl.java
src/main/java/com/varc/brewnetapp/domain/returning/command/application/service/ReturningServiceImpl.java

- feat: 반품/교환 sse 제거
- X
- feat: 반품/교환 sse 제거
- X
- 사진을 업로드해주세요

feat: 반품/교환 sse 제거
